server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-container:1099/eureka
    register-with-eureka: false
    fetchRegistry: true
    registryFetchIntervalSeconds: 2

    