message-printer:
  signature: ${spring.application.name}:${random.value}
  user: '{cipher}35f227f3d0562e2c5129be06917e5f65af0185c44c9ebf15783052e042bed14a4362fdf677480a1a07bdbbc71b463afb'
  pass: '{cipher}66a41e7533ee86290b9b7c63bba4e714dbd03a9e6597e7b558cdc32d93714137da8acfc0102bd5a0eeb6a8856290accc'

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-container:1099/eureka/
  instance:
    instanceId: ${spring.application.name}:${spri‌​ng.application.insta‌​nce_id:${random.valu‌​e}}
  
logging:
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG