spring:
  application:
    name: message-printer
    
message-printer:
 signature: ${spring.application.name}:${random.value}

server:
 port: 0
 
eureka:
 client:
  serviceUrl:
   defaultZone: http://eureka-container:1099/eureka
 instance:
  instanceId: ${spring.application.name}:${spri‌​ng.application.insta‌​nce_id:${random.valu‌​e}}