server:
  port: 1099

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-container:1099/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    leaseExpirationDurationInSeconds: 6
    leaseRenewalIntervalInSeconds: 2
  server:
    response-cache-update-interval-ms: 2000