server:
 port: 1099

spring:
 application:
  name: registry-server

eureka:
 client:
  register-with-eureka: false
  fetch-registry: false
  service-url:
   defaultZone: http://localhost:1099/eureka
 decoderName: JacksonJson
 instance:
  leaseExpirationDurationInSeconds: 6
  leaseRenewalIntervalInSeconds: 2
 server:
  response-cache-update-interval-ms: 2000