server:
 port: 8080

spring:
 application:
  name: zuul-server

eureka:
 client:
  serviceUrl:
   defaultZone: http://eureka-container:1099/eureka
  register-with-eureka: false
  fetchRegistry: true
  registryFetchIntervalSeconds: 2
  
zuul:
 sensitiveHeaders: